name: deploy-client

on:
  push: # on deploy
    branches:
      - main
    paths:
      - 'client/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client && docker build -t $DOCKER_USERNAME/client .
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - run: docker push $DOCKER_USERNAME/client
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ${{ secrets.DIGITALOCEAN_CLUSTER_NAME }}
        env:
          DIGITALOCEAN_CLUSTER_NAME: ${{ secrets.DIGITALOCEAN_CLUSTER_NAME }}
      - run: kubectl rollout restart deployment client-depl
